#!/usr/bin/env python3
"""Assemble the test shaders with picasso and embed them as C arrays.

Usage: gen_shaders.py   (needs $DEVKITPRO/tools/bin/picasso)

The output, shaders/shaders.h, is committed so that the host test harness
can be built without devkitPro.
"""
import os
import struct
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SHADERS = [
    ("shbin_color", ["color.v.pica"]),
    ("shbin_texture", ["texture.v.pica"]),
    ("shbin_gsh_quad", ["passthru.v.pica", "quad.g.pica"]),
]


def main():
    picasso = os.path.join(os.environ.get("DEVKITPRO", "/opt/devkitpro"), "tools", "bin", "picasso")
    out = ["/* Generated by gen_shaders.py from the shaders/ sources -- do not edit. */",
           "#ifndef SUITE_SHADERS_H", "#define SUITE_SHADERS_H", "#include <stdint.h>", ""]
    with tempfile.TemporaryDirectory() as tmp:
        for name, sources in SHADERS:
            dst = os.path.join(tmp, name + ".shbin")
            subprocess.run([picasso, "-o", dst] + [os.path.join(HERE, "shaders", s) for s in sources], check=True)
            data = open(dst, "rb").read()
            data += b"\0" * (-len(data) % 4)
            words = struct.unpack("<%dI" % (len(data) // 4), data)
            out.append("static const uint32_t %s[%d] = {" % (name, len(words)))
            for i in range(0, len(words), 6):
                out.append("    " + ", ".join("0x%08X" % w for w in words[i:i + 6]) + ",")
            out.append("};")
            out.append("")
    out.append("#endif")
    with open(os.path.join(HERE, "shaders", "shaders.h"), "w") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    sys.exit(main())
